### ISSUE TITLE
Version x.x.x gets partially cut off on iOS due to Screen Safe Area 

### ISSUE THREAD

**Issue by ABUCKY0** [hman124/bell-countdown#13]
the margins in place don't account for the curve in the screen on iPhones.

**Comment by hman124** [comment]
This has been addressed in 2.1.4 by using css environment variables. I will leave this issue open as I can't test the ios app

**Comment by ABUCKY0** [comment]
Yeah it isn’t fixed, but it doesn’t affect anything major.
