### ISSUE TITLE
The Circular progress bars sometimes appear funky on PC.

### ISSUE THREAD

**Issue by ABUCKY0** [hman124/bell-countdown#15]
![image](https://user-images.githubusercontent.com/81783950/167667773-c010f688-b111-40d3-b0d2-6037c1b1e65a.png)

**Comment by hman124** [comment]
This is a bug related to resizing the page and how the re-rendering works.

**Comment by ABUCKY0** [comment]
Update: This is due to an issue with the library, and a replacement library will be found soon.

**Comment by hman124** [comment]
This problem has been fully addressed in version 2.1.4   A new radial counter library is being uttilized
