### ISSUE TITLE
B Lunch Schedule

### ISSUE THREAD

**Issue by ABUCKY0** [hman124/bell-countdown#19]
B lunch schedule is off. Lunch comes before 5Th period.

**Comment by hman124** [comment]
That is how it is supposed to be

![Screenshot_20220511-122021_Gallery.png](https://user-images.githubusercontent.com/66391679/167909507-cb0c7678-8b42-431c-80c5-2144b691aca4.png)

**Comment by ABUCKY0** [comment]
But the thing showed lunch after 5Th period. I mean unless you fixed it
